### ISSUE TITLE
can't connect to runtime (debug in flowhub)

### ISSUE THREAD

**Issue by 7yl4r** [noflo/noflo-browser-app#4]
When attempting to "debug in flohub", I always get this "runtime not available" error. 

![0](https://cloud.githubusercontent.com/assets/1051390/7498460/f6c31800-f3ee-11e4-8abf-36ca7d066ea5.PNG)
![1](https://cloud.githubusercontent.com/assets/1051390/7498462/f6eaef7e-f3ee-11e4-915c-906df7576fd0.PNG)
![2](https://cloud.githubusercontent.com/assets/1051390/7498461/f6d6ad66-f3ee-11e4-8ad7-02dd8ebee0e8.PNG)

I don't understand how the link works, but I do notice it is hard-coded so perhaps it is just outdated: `https://app.flowhub.io/#runtime/endpoint?protocol%3Dwebrtc%26address%3Dhttps%3A%2F%2Fapi.flowhub.io%235b6236c0-0ed2-4a04-9082-4512b0cd2a41`

This looks like it should be: `https://app.flowhub.io/#runtime/endpoint?protocol=webrtc&address=<runtime address>` if that is the case maybe the runtime address should be something like `http://noflojs.org/noflo-browser-app/noflo-browser-app.js`? [This address results in the same error though so perhaps that is not the problem at all.](https://app.flowhub.io/#runtime/endpoint?protocol%3Dwebrtc%26address%3Dhttp%3A%2F%2Fnoflojs.org%2Fnoflo-browser-app%2Fnoflo-browser-app.js).

**Comment by jonnor** [comment]
The address is a WebRTC sync server (api.flowhub.io) + client ID (by default the runtime UUID), so its not hardcoded. It refers to a particular *instance* of the app.js that is being run (the tab or browser).
I have experienced problems myself with WebRTC though. For me it works about every other time, which is obviously not good enough - but last time I tried I was not able to figure out where the issue occurred.
On the server side we do see some timeouts related to the WebRTC sync server. A quick look into that suggested that perhaps the Heroku HTTP frontend was causing problems, due to lack of session affinity.

**Comment by 7yl4r** [comment]
> refers to a particular instance of the app.js that is being run

Oh, I suppose I should be opening the link in a new tab then? (the architecture of this system still baffles me) After trying to open in a new tab a few times I did get it to work. 

Might adding `target="_blank"` to [the link](https://github.com/noflo/noflo-browser-app/blob/gh-pages/main.html#L11) at least improve the chance of success then?

**Comment by forresto** [comment]
@7yl4r :+1: meant to do that last time I messed with it.

**Comment by bergie** [comment]
Fixed in master with the new webpack build, as well as with the latest release: https://noflojs.org/noflo-browser-app/main.html

![screenshot 2017-01-10 at 13 10 47](https://cloud.githubusercontent.com/assets/3346/21805780/40f32056-d736-11e6-9cec-23cfd6e3a2de.png)
